
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action ArquivoAction;

	private global::Gtk.Action AbrirAction;

	private global::Gtk.Action SairAction;

	private global::Gtk.Action ArquivoAction1;

	private global::Gtk.Action openAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action AjudaAction;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action floppyAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar2;

	private global::Gtk.HBox hbox12;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Label informativeHeader;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.Label informativeDetails;

	private global::Gtk.Label GtkLabel5;

	private global::Gtk.CheckButton cbSortable;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeView;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox3;

	private global::Gtk.CheckButton filterCbApenasAtivos;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label4;

	private global::Gtk.Entry filterEntryCCO;

	private global::Gtk.Label label6;

	private global::Gtk.Entry filterEntryCNS;

	private global::Gtk.Label label22;

	private global::Gtk.Entry filterEntryCPF;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label19;

	private global::Gtk.Entry filterEntryNome;

	private global::Gtk.Label label20;

	private global::Gtk.Entry filterEntryDtNascimento;

	private global::Gtk.Label label1;

	private global::Gtk.Entry filterEntryMae;

	private global::Gtk.HBox hbox10;

	private global::Gtk.Label label14;

	private global::Gtk.Entry filterEntryCodigo;

	private global::Gtk.Label label18;

	private global::Gtk.Entry filterEntryPlanoAns;

	private global::Gtk.Label label24;

	private global::Gtk.Entry filterEntryCNPJ;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Button filterBtnApply;

	private global::Gtk.Button filterBtnClear;

	private global::Gtk.Label GtkLabel8;

	private global::Gtk.Statusbar statusBar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.ArquivoAction = new global::Gtk.Action("ArquivoAction", global::Mono.Unix.Catalog.GetString("Arquivo"), null, null);
		this.ArquivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Arquivo");
		w1.Add(this.ArquivoAction, null);
		this.AbrirAction = new global::Gtk.Action("AbrirAction", global::Mono.Unix.Catalog.GetString("Abrir..."), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Abrir...");
		w1.Add(this.AbrirAction, null);
		this.SairAction = new global::Gtk.Action("SairAction", global::Mono.Unix.Catalog.GetString("Sair"), null, null);
		this.SairAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Sair");
		w1.Add(this.SairAction, null);
		this.ArquivoAction1 = new global::Gtk.Action("ArquivoAction1", global::Mono.Unix.Catalog.GetString("Arquivo"), null, null);
		this.ArquivoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Arquivo");
		w1.Add(this.ArquivoAction1, null);
		this.openAction = new global::Gtk.Action("openAction", global::Mono.Unix.Catalog.GetString("Abrir..."), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Abrir...");
		w1.Add(this.openAction, "<Control>o");
		this.quitAction = new global::Gtk.Action("quitAction", global::Mono.Unix.Catalog.GetString("Sair"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Sair");
		w1.Add(this.quitAction, "<Alt>F4");
		this.AjudaAction = new global::Gtk.Action("AjudaAction", global::Mono.Unix.Catalog.GetString("Ajuda"), null, null);
		this.AjudaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Ajuda");
		w1.Add(this.AjudaAction, null);
		this.aboutAction = new global::Gtk.Action("aboutAction", global::Mono.Unix.Catalog.GetString("Sobre"), null, "gtk-about");
		this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Sobre");
		w1.Add(this.aboutAction, null);
		this.floppyAction = new global::Gtk.Action("floppyAction", global::Mono.Unix.Catalog.GetString("Exportar CSV"), null, "gtk-floppy");
		this.floppyAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exportar CSV");
		w1.Add(this.floppyAction, "<Primary>e");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 1024;
		this.HeightRequest = 768;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("CNXReader");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='ArquivoAction1' action='ArquivoAction1'><menuitem name='openAction' action='openAction'/><menuitem name='floppyAction' action='floppyAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='AjudaAction' action='AjudaAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add(this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame3.BorderWidth = ((uint)(5));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.informativeHeader = new global::Gtk.Label();
		this.informativeHeader.Name = "informativeHeader";
		this.informativeHeader.LabelProp = global::Mono.Unix.Catalog.GetString("Aguardando arquivo CNX.");
		this.GtkAlignment1.Add(this.informativeHeader);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Cabeçalho</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel4;
		this.hbox12.Add(this.frame3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.frame3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame5.BorderWidth = ((uint)(5));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.informativeDetails = new global::Gtk.Label();
		this.informativeDetails.Name = "informativeDetails";
		this.informativeDetails.LabelProp = global::Mono.Unix.Catalog.GetString("-");
		this.GtkAlignment2.Add(this.informativeDetails);
		this.frame5.Add(this.GtkAlignment2);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Detalhes</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel5;
		this.hbox12.Add(this.frame5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.frame5]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.cbSortable = new global::Gtk.CheckButton();
		this.cbSortable.WidthRequest = 150;
		this.cbSortable.CanFocus = true;
		this.cbSortable.Name = "cbSortable";
		this.cbSortable.Label = global::Mono.Unix.Catalog.GetString("Ordenação");
		this.cbSortable.DrawIndicator = true;
		this.cbSortable.UseUnderline = true;
		this.hbox12.Add(this.cbSortable);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.cbSortable]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 3;
		w9.Expand = false;
		this.vbox1.Add(this.hbox12);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox12]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(10));
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeView = new global::Gtk.TreeView();
		this.treeView.CanFocus = true;
		this.treeView.Name = "treeView";
		this.GtkScrolledWindow.Add(this.treeView);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w12.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame1.BorderWidth = ((uint)(5));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.filterCbApenasAtivos = new global::Gtk.CheckButton();
		this.filterCbApenasAtivos.CanFocus = true;
		this.filterCbApenasAtivos.Name = "filterCbApenasAtivos";
		this.filterCbApenasAtivos.Label = global::Mono.Unix.Catalog.GetString("Apenas Ativos");
		this.filterCbApenasAtivos.DrawIndicator = true;
		this.filterCbApenasAtivos.UseUnderline = true;
		this.vbox3.Add(this.filterCbApenasAtivos);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.filterCbApenasAtivos]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.WidthRequest = 45;
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("CCO");
		this.label4.Justify = ((global::Gtk.Justification)(1));
		this.hbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label4]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.filterEntryCCO = new global::Gtk.Entry();
		this.filterEntryCCO.WidthRequest = 150;
		this.filterEntryCCO.CanFocus = true;
		this.filterEntryCCO.Name = "filterEntryCCO";
		this.filterEntryCCO.IsEditable = true;
		this.filterEntryCCO.InvisibleChar = '●';
		this.hbox2.Add(this.filterEntryCCO);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.filterEntryCCO]));
		w15.Position = 1;
		w15.Expand = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("CNS");
		this.label6.Justify = ((global::Gtk.Justification)(1));
		this.hbox2.Add(this.label6);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label6]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.filterEntryCNS = new global::Gtk.Entry();
		this.filterEntryCNS.WidthRequest = 150;
		this.filterEntryCNS.CanFocus = true;
		this.filterEntryCNS.Name = "filterEntryCNS";
		this.filterEntryCNS.IsEditable = true;
		this.filterEntryCNS.InvisibleChar = '●';
		this.hbox2.Add(this.filterEntryCNS);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.filterEntryCNS]));
		w17.Position = 3;
		w17.Expand = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("CPF");
		this.hbox2.Add(this.label22);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label22]));
		w18.Position = 4;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.filterEntryCPF = new global::Gtk.Entry();
		this.filterEntryCPF.WidthRequest = 150;
		this.filterEntryCPF.CanFocus = true;
		this.filterEntryCPF.Name = "filterEntryCPF";
		this.filterEntryCPF.IsEditable = true;
		this.filterEntryCPF.InvisibleChar = '●';
		this.hbox2.Add(this.filterEntryCPF);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.filterEntryCPF]));
		w19.Position = 5;
		w19.Expand = false;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label();
		this.label19.WidthRequest = 45;
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Nome");
		this.label19.Justify = ((global::Gtk.Justification)(1));
		this.hbox4.Add(this.label19);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label19]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.filterEntryNome = new global::Gtk.Entry();
		this.filterEntryNome.WidthRequest = 250;
		this.filterEntryNome.CanFocus = true;
		this.filterEntryNome.Name = "filterEntryNome";
		this.filterEntryNome.IsEditable = true;
		this.filterEntryNome.InvisibleChar = '●';
		this.hbox4.Add(this.filterEntryNome);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.filterEntryNome]));
		w22.Position = 1;
		w22.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Data Nascimento");
		this.hbox4.Add(this.label20);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label20]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.filterEntryDtNascimento = new global::Gtk.Entry();
		this.filterEntryDtNascimento.WidthRequest = 120;
		this.filterEntryDtNascimento.CanFocus = true;
		this.filterEntryDtNascimento.Name = "filterEntryDtNascimento";
		this.filterEntryDtNascimento.IsEditable = true;
		this.filterEntryDtNascimento.InvisibleChar = '●';
		this.hbox4.Add(this.filterEntryDtNascimento);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.filterEntryDtNascimento]));
		w24.Position = 3;
		w24.Expand = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mãe");
		this.hbox4.Add(this.label1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label1]));
		w25.Position = 4;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.filterEntryMae = new global::Gtk.Entry();
		this.filterEntryMae.WidthRequest = 250;
		this.filterEntryMae.CanFocus = true;
		this.filterEntryMae.Name = "filterEntryMae";
		this.filterEntryMae.IsEditable = true;
		this.filterEntryMae.InvisibleChar = '●';
		this.hbox4.Add(this.filterEntryMae);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.filterEntryMae]));
		w26.Position = 5;
		w26.Expand = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label14 = new global::Gtk.Label();
		this.label14.WidthRequest = 45;
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Código");
		this.hbox10.Add(this.label14);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label14]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.filterEntryCodigo = new global::Gtk.Entry();
		this.filterEntryCodigo.WidthRequest = 150;
		this.filterEntryCodigo.CanFocus = true;
		this.filterEntryCodigo.Name = "filterEntryCodigo";
		this.filterEntryCodigo.IsEditable = true;
		this.filterEntryCodigo.InvisibleChar = '●';
		this.hbox10.Add(this.filterEntryCodigo);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.filterEntryCodigo]));
		w29.Position = 1;
		w29.Expand = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label();
		this.label18.WidthRequest = 65;
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Plano ANS");
		this.hbox10.Add(this.label18);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label18]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.filterEntryPlanoAns = new global::Gtk.Entry();
		this.filterEntryPlanoAns.WidthRequest = 150;
		this.filterEntryPlanoAns.CanFocus = true;
		this.filterEntryPlanoAns.Name = "filterEntryPlanoAns";
		this.filterEntryPlanoAns.IsEditable = true;
		this.filterEntryPlanoAns.InvisibleChar = '●';
		this.hbox10.Add(this.filterEntryPlanoAns);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.filterEntryPlanoAns]));
		w31.Position = 3;
		w31.Expand = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label24 = new global::Gtk.Label();
		this.label24.Name = "label24";
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("CNPJ Empresa");
		this.hbox10.Add(this.label24);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label24]));
		w32.Position = 4;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.filterEntryCNPJ = new global::Gtk.Entry();
		this.filterEntryCNPJ.WidthRequest = 150;
		this.filterEntryCNPJ.CanFocus = true;
		this.filterEntryCNPJ.Name = "filterEntryCNPJ";
		this.filterEntryCNPJ.IsEditable = true;
		this.filterEntryCNPJ.InvisibleChar = '●';
		this.hbox10.Add(this.filterEntryCNPJ);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.filterEntryCNPJ]));
		w33.Position = 5;
		w33.Expand = false;
		this.vbox3.Add(this.hbox10);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox10]));
		w34.Position = 3;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.filterBtnApply = new global::Gtk.Button();
		this.filterBtnApply.WidthRequest = 100;
		this.filterBtnApply.CanFocus = true;
		this.filterBtnApply.Name = "filterBtnApply";
		this.filterBtnApply.UseUnderline = true;
		this.filterBtnApply.Label = global::Mono.Unix.Catalog.GetString("Buscar");
		global::Gtk.Image w35 = new global::Gtk.Image();
		w35.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-find", global::Gtk.IconSize.Button);
		this.filterBtnApply.Image = w35;
		this.hbox13.Add(this.filterBtnApply);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.filterBtnApply]));
		w36.Position = 0;
		w36.Expand = false;
		w36.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.filterBtnClear = new global::Gtk.Button();
		this.filterBtnClear.WidthRequest = 100;
		this.filterBtnClear.CanFocus = true;
		this.filterBtnClear.Name = "filterBtnClear";
		this.filterBtnClear.UseUnderline = true;
		this.filterBtnClear.Label = global::Mono.Unix.Catalog.GetString("Limpar");
		global::Gtk.Image w37 = new global::Gtk.Image();
		w37.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-clear", global::Gtk.IconSize.Button);
		this.filterBtnClear.Image = w37;
		this.hbox13.Add(this.filterBtnClear);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.filterBtnClear]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		this.vbox3.Add(this.hbox13);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox13]));
		w39.PackType = ((global::Gtk.PackType)(1));
		w39.Position = 4;
		w39.Expand = false;
		w39.Fill = false;
		this.GtkAlignment.Add(this.vbox3);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel8 = new global::Gtk.Label();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Filtros</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel8;
		this.vbox1.Add(this.frame1);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
		w42.Position = 3;
		w42.Expand = false;
		w42.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusBar = new global::Gtk.Statusbar();
		this.statusBar.Name = "statusBar";
		this.statusBar.Spacing = 6;
		this.vbox1.Add(this.statusBar);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusBar]));
		w43.Position = 4;
		w43.Expand = false;
		w43.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1024;
		this.DefaultHeight = 768;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.AbrirAction.Activated += new global::System.EventHandler(this.OnAbrir);
		this.SairAction.Activated += new global::System.EventHandler(this.OnSair);
		this.openAction.Activated += new global::System.EventHandler(this.OnAbrir);
		this.quitAction.Activated += new global::System.EventHandler(this.OnSair);
		this.aboutAction.Activated += new global::System.EventHandler(this.OnSobre);
		this.floppyAction.Activated += new global::System.EventHandler(this.OnExport);
		this.filterEntryCCO.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryCNS.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryCPF.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryNome.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryDtNascimento.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryMae.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryCodigo.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryPlanoAns.Activated += new global::System.EventHandler(this.OnEntryActived);
		this.filterEntryCNPJ.Activated += new global::System.EventHandler(this.OnEntryActived);
	}
}
